# Generated by Django 2.0.8 on 2018-09-28 06:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=200)),
                ('create_at', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('updated_at', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('aproved', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=1000)),
                ('create_at', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('updated_at', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('aproved', models.BooleanField(default=True)),
                ('tags', models.CharField(max_length=20)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Categories')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Posts'),
        ),
    ]
