# Generated by Django 2.0.8 on 2018-09-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='arthor_name',
            field=models.CharField(default='Omar', max_length=20),
        ),
        migrations.AddField(
            model_name='posts',
            name='sub_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
